### PR TITLE
Algorithm input

### LINKED ISSUE #7: Algorithms should accept String or Buffer input
Data input to algorithms should be able to accept both String and Buffer input, as can be seen in AES-GCM's `encrypt` and `decrypt` functions.

### PR DESCRIPTION
**Pull request by johnny90**
Added support for both String and Buffer input
Added missing tests

Closes #7

### CODE REVIEW

**Comment by EternalDeiwos** [comment]
Thanks for PR. Changes look great and all tests are passing. Particularly happy with the additional thorough test coverage.

Was wondering if we could do a couple style changes before we merge? Something like:

https://github.com/anvilresearch/jwa/blob/36f46732d628bda6551ce659a307add06492da25/src/algorithms/AES-GCM.js#L91-L103

If we space it out a little and include some commentary -- not for the comments to be useful but rather to separate the blocks of code and make it easier to read -- it could look like this:

```js
decrypt (key, ciphertext, iv, tag, aad) { 
  let algorithm = this.params 

  // Normalize iv input
  if (typeof iv === 'string') { 
    iv = Uint8Array.from(base64url.toBuffer(iv))
  } else { 
    iv = Uint8Array.from(iv) 
  } 

  // Assign non-enumerable iv
  Object.defineProperty(algorithm, 'iv', { 
    enumerable: false, 
    configurable: true, 
    value: iv 
  })

  ...
}
```

If you could follow this pattern across the various algorithms then it would go a long way to keeping the library maintainable.

**Comment by christiansmith** [comment]
I agree with Greg's proposed spacing. It's been the tacitly agreed upon style in previous work. We should open a "code style guide" issue on trustdata/org to collect all these things for discussion and eventually to publish a reference document.

**Comment by christiansmith** [comment]
Also, great job @johnny90 =]

**Review by EternalDeiwos — APPROVED** [review]
Looks great. Thanks for the hard work.

**Pull request merged**
